pipeline {
  agent none
  options {
    timeout(time: 30, unit: 'MINUTES')
  }
  stages {
    stage('Build') {
      agent {
        kubernetes {
          cloud 'kubernetes'
          inheritFrom 'node'
          yaml '''apiVersion: v1
                  kind: Pod
                  metadata:
                    name: node-16
                    labels:
                      name: node-16
                  spec:
                    containers:
                    - name: node
                      image: node:16.20.2-alpine
                      resources:
                        limits:
                          memory: "2Gi"
                          cpu: "1"
                '''
        }
      }
      steps {
        dir('src/backend') {
          script {
            npm ci
          }  
        }
      }
    }
  }
}