pipeline {
  agent none
  options {
    timeout(time: 30, unit: 'MINUTES')
  }
  stages {
    stage('Build') {
      agent {
        kubernetes {
          cloud 'kubernetes'
          yaml '''
            apiVersion: v1
            kind: Pod
            metadata:
              name: node-16
              labels:
                name: node-16
            spec:
              containers:
              - name: node
                image: node:16.20.2-alpine
                tty: true
                resources:
                  limits:
                    memory: "2Gi"
                    cpu: "1"
                '''
        }
      }
      steps {
        container('node') {
          sh 'cd src/backend && npm ci'
        }
        // dir('src/backend') {
        //   script {
        //     npm ci
        //   }  
        // }
      }
    }
  }
}