pipeline {
  agent none
  options {
    timeout(time: 30, unit: 'MINUTES')
  }
  stages {
    stage('Build') {
      agent {
        kubernetes {
          cloud 'kubernetes'
          yaml '''
            apiVersion: v1
            kind: Pod
            metadata:
              name: node-16
              labels:
                name: node-16
            spec:
              containers:
              - name: docker
                image: docker:latest
                tty: true
                volumeMounts:
                - mountPath: /var/run/docker.sock
                  name: docker-sock
                resources:
                  limits:
                    memory: "2Gi"
                    cpu: "1"
              volumes:
              - name: docker-sock
                hostPath:
                  path: /var/run/docker.sock
                '''
        }
      }
      steps {
        container('docker') {
          sh 'cd src/backend && docker build --tag ntg-garage-backend:latest .'
        }
        // dir('src/backend') {
        //   script {
        //     npm ci
        //   }  
        // }
      }
    }
  }
}