pipeline {
  agent none
  options {
    timeout(time: 30, unit: 'MINUTES')
  }
  stages {
    stage('BuildAndPush') {
      agent {
        kubernetes {
          cloud 'kubernetes'
          yaml '''
            apiVersion: v1
            kind: Pod
            metadata:
              name: kaniko
            spec:
              containers:
              - name: kaniko
                image: gcr.io/kaniko-project/executor:debug
                imagePullPolicy: Always
                tty: true
                command: 
                - /busybox/sh
                resources:
                  limits:
                    cpu: '1'
                    memory: 2Gi
                '''
        }
      }
      environment {
        AWS_ACCESS_KEY_ID = credentials("AWS_ACCESS_KEY_ID")
        AWS_SECRET_ACCESS_KEY = credentials("AWS_SECRET_ACCESS_KEY")
      }
      steps {
        container('kaniko') {
          sh "cd src/frontend && /kaniko/executor --dockerfile ./Dockerfile --context dir://\$(pwd) --destination \${AWS_REGISTRY}/ntg-garage-frontend:latest"
        }
      }
    }
  }
}